### ISSUE TITLE
https://riotquest.supergrecko.dev/ - Documentation server unavailable.

### ISSUE THREAD

**Issue by rwhol** [supergrecko/RiotQuest#26]

**Comment by supergrecko** [comment]
I'm not having any issues viewing it but that might be my DNS cache. I'll poke around and see what I find. I'll also set up a mirror on netlify.

**Comment by supergrecko** [comment]
There was an issue on my end with my domain registrar. I will resolve that soon. Until that is fixed you can use the mirror I set up at https://riotquest.netlify.com
