### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by rwhol** [supergrecko/RiotQuest#27]
In the documentation the following is mentioned:

>You'll need two environment variables to use RiotQuest.
>RIOTQUEST_STANDARD_KEY=RGAPI-1234-abcd.... # Riot Games API key
>RIOTQUEST_STANDARD_LIMIT=60:20 # 60 requests every 20 seconds

Wouldn't a better solution be to read the limit from the response header of the Riot API (`X-App-Rate-Limit`) and adjust automatically based on that? 
Riots own documentation suggests that you should never hard code any values for rate limiting as they can change at any time.

**Comment by supergrecko** [comment]
RiotQuest reads the limits off of the headers as well, the env variables are a "soft limit"

**Comment by supergrecko** [comment]
Just to give you a progress update, I should have the new rate limit implementation out later today. The environment variable will also be gone.

**Comment by supergrecko** [comment]
This issue has been resolved as of v1.3.0
