### ISSUE TITLE
List of Matchs

### ISSUE THREAD

**Issue by darwiky** [supergrecko/RiotQuest#29]
this code is the one i was using to get only matchs from Season 2014 and reports 0 games when it should show all games played in that season.
```
include ('vendor/autoload.php');
use RiotQuest\Client;
Client::boot();

$accountid = $_GET["id"];

$data = Client::Match('euw')->list($accountid)->getWhereSeason ("4")->getWhereQueue("420");
```
when using this code

```
include ('vendor/autoload.php');
use RiotQuest\Client;
Client::boot();

$accountid = $_GET["id"];

$data = Client::Match('euw')->list($accountid);
```

only show 100 games from 2051 games how can i get the full list?

**Comment by supergrecko** [comment]
Hello, the Riot API only stores matches for two years which means that 2014 games are not available from the API.

You can set the startIndex to 101 to get the second page
```php
Client::match('euw')->list($id, ['startIndex' =>101]);
