### ISSUE TITLE
Filter Stats

### ISSUE THREAD

**Issue by darwiky** [supergrecko/RiotQuest#30]
How can i filter this stats
![image](https://user-images.githubusercontent.com/53486744/62815586-9ed3d900-bb12-11e9-9c6e-2680124dea08.png)

to get on 5,10,15,20,25,30min?

i dont see on your documentation how to interect with them since on riot it says that is possible to do it

![image](https://user-images.githubusercontent.com/53486744/62815602-d2aefe80-bb12-11e9-931e-4115e5eca3ac.png)

**Comment by supergrecko** [comment]
This object is accessible via
```php
$match->participants[0...9]->timeline
```

You can only get the intervals 0-10, 10-20, 20-30 and so on as the Riot only reports this data every 10th minute.

**Comment by darwiky** [comment]
if i want to get 30-40 i will have to do something like
`$match->participants[0...9]->timeline["...."]["30-40"]`

**Comment by darwiky** [comment]
for what im reading is impossible to get this data above 30min..thanks for your time ^^ and good work
