### ISSUE TITLE
v1.3.1 Error (code 3)

### ISSUE THREAD

**Issue by WildEgo** [supergrecko/RiotQuest#46]
**Describe the bug**
The error persists, should be manifest.json related but not sure

**To Reproduce**
1. use RiotQuest\Client as LeagueAPI;
2. return LeagueAPI::summoner(strtolower($result->server))->name($result->account_ign);
3. "ERROR (code 3): Internal Service Error. Please report this error by opening an issue on GitHub."

**Expected behavior**
Should've returned anything that is not an error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PHP Version: 7.2.10
 - RiotQuest Version: ^1.3.1

**SCREENSHOT**
https://i.imgur.com/eSVvnxU.png

**Comment by supergrecko** [comment]
I'm currently unable to reproduce, can you add this `echo $ex->getTraceAsString();` after Line 110 `src/RiotQuest/Components/Engine/Request.php` inside your vendor and tell me what you get?

**Comment by WildEgo** [comment]
> $ex->getTraceAsString();

`[2019-09-14 15:23:54] local.INFO: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', 'E:\\XAMPP\\htdocs...', 42, Array)
#1 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\DataProviders\BaseProvider.php(42): file_get_contents('E:\\XAMPP\\htdocs...')
#2 [internal function]: RiotQuest\Components\DataProviders\BaseProvider::onEnable()
#3 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Client\Application.php(115): call_user_func(Array)
#4 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Client\Client.php(31): RiotQuest\Components\Client\Application->load()
#5 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Client\Application.php(175): RiotQuest\Components\Client\Client::boot()
#6 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Engine\Request.php(97): RiotQuest\Components\Client\Application::log('INFO', 'Accessing {endp...', Array)
#7 E:\XAMPP\htdocs\*****\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Endpoints\Summoner.php(55): RiotQuest\Components\Engine\Request->send()
#8 E:\XAMPP\htdocs\*****\app\Http\Controllers\UserOrderController.php(49): RiotQuest\Components\Endpoints\Summoner->name('*INGAMENAME*')
#9 [internal function]: App\Http\Controllers\UserOrderController->index('317')
#10 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#11 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
#12 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\UserOrderController), 'index')
#13 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#14 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Router.php(680): Illuminate\Routing\Route->run()
#15 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 E:\XAMPP\htdocs\*****\app\Http\Middleware\isBuyer.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\isBuyer->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 E:\XAMPP\htdocs\*****\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 E:\XAMPP\htdocs\*****\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 E:\XAMPP\htdocs\*****\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}  `

**Comment by supergrecko** [comment]
I believe the latest tag `1.3.2` should fix this now. It appears that the manifest.json file was not added to git which is why I was not able to reproduce your error. It has now been added to git and if it's not there it will create itself.

Let me know if you're still having issues.

**Comment by WildEgo** [comment]
different problem was created

`[2019-09-14 15:50:06] local.INFO: #0 E:\XAMPP\htdocs\******\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Client\Application.php(128): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'E:\\XAMPP\\htdocs...', 128, Array)`

also you forgot to delete the echo from the catch

**Comment by supergrecko** [comment]
Alright, I believe it should all be fixed now. The error was caused by attempting to access an environment index instead of using isset(). This is now resolved in `1.3.3`

**Comment by WildEgo** [comment]
on
`\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Client\Application.php`

`"A void function must not return a value"`

**Comment by supergrecko** [comment]
Fixed in `1.3.4`

**Comment by WildEgo** [comment]
Everything looks perfect indeed I'll close it myself thanks for the help!
