### ISSUE TITLE
Set ->getRanked() cache time

### ISSUE THREAD

**Issue by WildEgo** [supergrecko/RiotQuest#60]
**Is your feature request related to a problem? Please describe.**
The main problem is getting fresh ranked data that is not stored for 1 hour.

**Describe the solution you'd like**
Give me a parameter to set the cache time on the spot.

**Describe alternatives you've considered**
Give us the chance to set a environment variable with the default TTL.

**Code examples, if applicable**
$summoner_api->getRanked(60);

**Comment by supergrecko** [comment]
Hey, I'm currently out of town for a few days, but I'll definitely add support for this.

**Comment by WildEgo** [comment]
Thanks man for the meantime I just hardcoded it into summoner.php since it's not a production thing keep me updated!

**Comment by supergrecko** [comment]
This has been added under `1.4.0`. The documentation will be updated shortly.
