### ISSUE TITLE
Laravel 6 support ?

### ISSUE THREAD

**Issue by elreco** [supergrecko/RiotQuest#64]
Hello,

thank you so much for your package. Can you add a laravel 6 support please ?

thank you

**Comment by supergrecko** [comment]
Hi, I see you've made some minor changes to your fork, are these the changes you'd wish to introduce or is there something else Laravel related?

There is an existing ServiceProvider which was written when Laravel 5 was the latest release. I peeked around and I didn't see any major changes for Service Providers. There has been some troubles with this not registering in the past though.

Could you elaborate on which changes/additions need to be added for Laravel 6 support?

**Comment by elreco** [comment]
Hello, 

sorry I forked your repo but it was because I had a bug with the $_ENV variable, I don't know why it returns a null value sometimes.

I will delete the repo, I just downgraded my laravel project to 5.8. I don't need v6 for the moment.

Thank you for the support!

**Comment by supergrecko** [comment]
If you want to you can PR your fork into mine. We're currently depending on `illuminate/support` so we can use `env()` instead as it looks a little bit nicer.

I'll implement it if you don't PR it :P
