### ISSUE TITLE
API Key not being found in Production

### ISSUE THREAD

**Issue by WildEgo** [supergrecko/RiotQuest#69]
**Describe the bug**
The API Key is not found when in production (using laravel)

**To Reproduce**
1. Just a normal call.

**Expected behavior**
Finding the key since the key is set on the .env file both the main .env as the .env in the folder itself

**Screenshots**
https://i.ibb.co/HV7jfKB/aaaaaa.png

**Desktop (please complete the following information):**
 - OS: CENTOS 7.4
 - PHP Version: 7.2
 - RiotQuest Version: 1.5.0 (can't update to latest since I'm using laravel 5.8)

**Comment by WildEgo** [comment]
First didn't work composer update didn't work, update didn't update anything, any ideas?

**Comment by supergrecko** [comment]
Hi, I've figured out why it wasn't working. It appears that the engine uses `strtolower` on the file name. The reason it would work on my setup is because Windows ignores case in file names whereas Unix systems don't ignore it.

I'll be pushing a new release which fixes this issue asap.

**Comment by WildEgo** [comment]
Please be sure it works with laravel 5.8 or lower since ur current dependencies kill any chance of me updating it

**Comment by supergrecko** [comment]
Yeah, I'll work out the dependencies as well

**Comment by WildEgo** [comment]
Thanks man I really appreciate

**Comment by junlarsen** [comment]
Pushed a new release, 1.5.2

Let me know if you still have problems with dependencies or anything by opening a new issue
