### ISSUE TITLE
[QUESTION] How to get current summoner's name from LoL client

### ISSUE THREAD

**Issue by lucianobosco** [supergrecko/RiotQuest#71]
I'm new on this API. Just wondering how to get real-time summoner's name from LoL client when joining a match. Is this possible?
I'm aware that OP.GG does it through their Chrome extension, but not sure how it can be done or we have other options. 
I know that a simple way could be by filling your summoner name in a website form and refreshing once you join a match, but I'd like to do it without user intervention. 
This package looks very interesting!

**Comment by junlarsen** [comment]
Hi, this library does not support the League Client APIs as PHP is not a very good language for working with asynchronous code.

OP.GG uses the League Client Update APIs (https://developer.riotgames.com/docs/lol#league-client)

You can probably get a good answer for your question in the Riot Games API Discord (https://discord.gg/riotapi)
